services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmqnotificationservice
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  mongodb:
    image: mongo:7
    container_name: mongodbnotificationservice
    ports:
      - "27017:27017"
