spring.application.name=notificationservice

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.data.mongodb.uri=mongodb://guest:guest@localhost:27017/